### PR TITLE
Changed And Added New Icons

### PR DESCRIPTION
**Pull request by agam778**
Changed some of the JetBrains icons cause the old ones weren't good and added Davinci Resolve icon and fixed Etcher icon

### CODE REVIEW

**Comment by vinceliuice** [comment]
It's all png files?

**Comment by vinceliuice** [comment]
Just send me a copy, I need use inkscape remake it to standard svg files that it will not get blur when you use it on HD display

**Comment by agam778** [comment]
Well, they are the SVG files only?

**Comment by agam778** [comment]
Ok wait the Davinci Resolve Icon is png 😅

**Comment by vinceliuice** [comment]
The others are all put a png file into a svg, that'll still get blur when you use it, so I need to remake them all

**Comment by vinceliuice** [comment]
Never mind, I'll do the job!

**Comment by agam778** [comment]
Well, I took the icons from https://macosicons.com

**Comment by vinceliuice** [comment]
Thanks, I finished!

**Pull request closed without merging**
