### PR TITLE
add missed zstd and archlinux package

### PR DESCRIPTION
**Pull request by ZorinArch**
Hi @vinceliuice 

This is some missed mimetype.

Thanks,

### CODE REVIEW

**Comment by Rippanda12** [comment]
id like to see this get added

**Comment by osamabinazam** [comment]
After upgrading to Gnome version 43, the WhiteSur theme is not reflected in all gnome apps such as nautilus, gnome-setting

**Comment by vinceliuice** [comment]
@osamabinazam  Run `./install.sh -l` in WhiteSur gtk theme folder

**Comment by osamabinazam** [comment]
> @osamabinazam Run `./install.sh -l` in WhiteSur gtk theme folder
Still getting errors during the installation

**Comment by vinceliuice** [comment]
@osamabinazam Download from here: https://github.com/vinceliuice/WhiteSur-gtk-theme

**Comment by osamabinazam** [comment]
@vinceliuice Still not reflecting 

Screenshot from 2022-11-20 03-06-30
Screenshot from 2022-11-20 03-08-39

**Comment by vinceliuice** [comment]
@osamabinazam  What error info after you run `./install.sh -l` ? show me the terminal output

**Pull request closed without merging**
